## Path to sample sheet
samplesheet: 'ATACsamplesheet.txt'

## List columns to concatenate for file names 
## (or indicate a single Name column, i.e. fileNamesFrom: ['Name'])
fileNamesFrom: ['Project', 'Cell_Type', 'Time', 'Bio_Rep', 'Tech_Rep']

## List columns to group (i.e. any columns left out will become part of the same group)
## set mergeBy: '' for no merging 
mergeBy: ['Project', 'Cell_Type', 'Time']

## Indicate whether to create stranded signal tracks
stranded: False

## Genome-specific reference parameters (choose correct genome build!)
## bwamem: '/proj/seq/data/HG19_UCSC/Sequence/BWAIndex/genome.fa'
bwamem: '/proj/seq/data/hg38_UCSC/Sequence/BWAIndex/genome.fa'


## Software versions
fastqcVers: "0.11.9"
trimVers: "0.6.7"
bwaVers: "0.7.17"
samtoolsVers: "1.17"
javaVers: "17.0.2"
deeptoolsVers: "3.5.1"
multiqcVers: "1.11" 
bedtoolsVers: "2.30"
macsVers: "2016-02-15"
