__default__:
  name: "{rule},{wildcards}" # -J
  partition: general # -p
  time: 4320 # -t
  cpusPerTask: "{threads}" # -c
  memPerCpu: 64G # --mem-per-cpu
  nodes: 1
  output: "output/logs_slurm/{rule}.{wildcards}.{jobid}.out"
  error: "output/logs_slurm/{rule}.{wildcards}.{jobid}.err"

## Multi-threaded / High-memory Rules
quant:
  memPerCpu: 20G

align:
  memPerCpu: 8G
