## Path to sample sheet
samplesheet: 'RNAsamplesheet.txt'

## List columns to concatenate for file names 
## (or indicate a single Name column, i.e. fileNamesFrom: ['Name'])
fileNamesFrom: ['Project', 'Cell_Type', 'Genotype', 'Time', 'Bio_Rep', 'Tech_Rep']

## List columns to group (i.e. any columns left out will become part of the same group)
## set mergeBy: '' for no merging
mergeBy: ['Project', 'Cell_Type', 'Genotype']

## Indicate whether to create stranded signal tracks
stranded: True # False

## Genome-specific reference parameters
salmon: '/proj/seq/data/salmon_RNAseq_genomes/hg38_cdna/salmon_index/default'
hisat2: '/proj/seq/data/hg38_UCSC/Sequence/HISAT2Index/genome'
gtf: '/proj/seq/data/GRCh38_GENCODE/gencode.v32.primary_assembly.annotation.gtf'

## Software versions
fastqcVers: "0.11.5"
trimVers: "0.6.7"
salmonVers: "1.4.0"
hisatVers: "2.1.0"
samtoolsVers: "1.9"
deeptoolsVers: "3.0.1"
multiqcVers: "1.5" 
rVers: "3.3.1"
